sudo: required

branches:
  only:
    - master

services:
  - docker

script:
  - docker-compose -f docker-compose.travis.yml up -d
  - docker-compose -f docker-compose.travis.yml exec tell-me-a-secret sbt -Dsbt.supershell=false clean compile test it:test
