version: '3'
services:
  tell-me-a-secret:
    image: hseeberger/scala-sbt:8u222_1.3.2_2.13.8
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      REDIS_HOST: "redis"
    depends_on:
      - redis
    command: sleep 5000
  redis:
    image: redis:5.0.4
